### PR TITLE
Fix handling of new implementation deployments

### LINKED ISSUE #438: Fix handling of deployment of new implementations in ProxyUpgrader
**Issue:** In order to release a nonce, we must detect if a transaction was created or not, instead of relying only on the difference between the addresses.

Example where current implementation is wrong:

1. We create two ProxyUpgrader for the same contract name.
2. When preparing the upgrade, the first will create a transaction to deploy the new implementation -> the old implementation is different than the new. -> Nonce is not released, correct so far.
3. When the seccond prepared the upgrade, no new transaction will be created because the old implementation address will be reused (from manifest) - the old implementation is different than the new -> Nonce is NOT released, **Incorrect**.

### PR DESCRIPTION
**Pull request by eduv09**
Fixes #438

### CODE REVIEW

File: src/proxyUpgrader.ts [hunk 1]
```diff
@@ -80,26 +81,44 @@ export abstract class ProxyUpgrader {
...
             console.log(chalk.gray(`Contract ${this.contractName} is up to date`));
-            // Release only if no upgrade is needed
+        } else {
+            this.newImplementationAddress = newImplementationAddress;
+        }
+    }
+
+    private async resolveDeployment(response: DeployImplementationResponse, nonce?: number): Promise<string> {
+        // If return is string, means no deployment transaction was required
+        if (typeof response === "string") {
```
Comment (DimaStebaev) [inline src/proxyUpgrader.ts]: Maybe use `isAddress` here?
https://docs.ethers.org/v6/api/address/#isAddress

**Review by DimaStebaev — APPROVED** [review]
